# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38f3526dcdd2476f9e10fdcb3580bceb75c708ab36795ace36ba4d3e3d5c60926ec66a98d4a62aab5f32b16c747f98f7b708ef73fe4055514dc287385096633

test:
  secret_key_base: 636b4f509a907f70a46b999f86c41a6e9bf7b806679cd7123f5b5de4f7f1cd0bbd46d2b77127e1414a48716b005580b1ecd5f5551166fc890228ba97eb15434d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
