# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e792e4df298d17588b02b5c45b934008125f07195b7be6159165255602534681bfbf70588fb1c4cc95c1975972e7dfe50f1b087cce914734f27f0f6cfa6c6a73

test:
  secret_key_base: d41bd4dc165598b0282c5ad1a2d7f2813e486474f768142d698a28b58f4bdaeecd05c65fa6dfe79a155a7095ec97eca222ad40668294664a5c47fa7c34c8daf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
